mongo:
  image: mongo:3.2
  command: --nojournal
orion:
  image: fiware/orion
  links:
    - mongo
  ports:
    - "1026:1026"
  command: -dbhost mongo
fiware-sth:
  image: telefonicaiot/fiware-sth-comet
  links:
    - mongo
  ports:
    - "8666:8666"
  environment:
    - STH_HOST=0.0.0.0
    - DB_URI=mongo:27017
