version: '2'
services:
  nodered:
    image: docker.inter-iot.eu/inter-as-node-red
    volumes:
      - ./nodered-data:/data
    networks:
      main:
        aliases:
          - nodered
    ports:
      - "1880:1880"
networks:
  main:
